# Generated by Django 5.1.6 on 2025-02-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
